language: generic
sudo: required
services: 
  - docker 

before_install:
  - docker build -t sekkajin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sekkajin/docker-react npm run test
